(ns clj-ipfs-api.commands)

(def cmd-vecs
 [["add"]
  ["bitswap"]
  ["bitswap" "ledger"]
  ["bitswap" "reprovide"]
  ["bitswap" "stat"]
  ["bitswap" "wantlist"]
  ["block"]
  ["block" "get"]
  ["block" "put"]
  ["block" "rm"]
  ["block" "stat"]
  ["bootstrap"]
  ["bootstrap" "add"]
  ["bootstrap" "add" "default"]
  ["bootstrap" "list"]
  ["bootstrap" "rm"]
  ["bootstrap" "rm" "all"]
  ["cat"]
  ["cid"]
  ["cid" "base32"]
  ["cid" "bases"]
  ["cid" "codecs"]
  ["cid" "format"]
  ["cid" "hashes"]
  ["commands"]
  ["config"]
  ["config" "edit"]
  ["config" "profile"]
  ["config" "profile" "apply"]
  ["config" "replace"]
  ["config" "show"]
  ["daemon"]
  ["dag"]
  ["dag" "get"]
  ["dag" "put"]
  ["dag" "resolve"]
  ["dht"]
  ["dht" "findpeer"]
  ["dht" "findprovs"]
  ["dht" "get"]
  ["dht" "provide"]
  ["dht" "put"]
  ["dht" "query"]
  ["diag"]
  ["diag" "cmds"]
  ["diag" "cmds" "clear"]
  ["diag" "cmds" "set-time"]
  ["diag" "sys"]
  ["dns"]
  ["file"]
  ["file" "ls"]
  ["files"]
  ["files" "chcid"]
  ["files" "cp"]
  ["files" "flush"]
  ["files" "ls"]
  ["files" "mkdir"]
  ["files" "mv"]
  ["files" "read"]
  ["files" "rm"]
  ["files" "stat"]
  ["files" "write"]
  ["filestore"]
  ["filestore" "dups"]
  ["filestore" "ls"]
  ["filestore" "verify"]
  ["get"]
  ["id"]
  ["init"]
  ["key"]
  ["key" "gen"]
  ["key" "list"]
  ["key" "rename"]
  ["key" "rm"]
  ["log"]
  ["log" "level"]
  ["log" "ls"]
  ["log" "tail"]
  ["ls"]
  ["mount"]
  ["name"]
  ["name" "publish"]
  ["name" "pubsub"]
  ["name" "pubsub" "cancel"]
  ["name" "pubsub" "state"]
  ["name" "pubsub" "subs"]
  ["name" "resolve"]
  ["object"]
  ["object" "data"]
  ["object" "diff"]
  ["object" "get"]
  ["object" "links"]
  ["object" "new"]
  ["object" "patch"]
  ["object" "patch" "add-link"]
  ["object" "patch" "append-data"]
  ["object" "patch" "rm-link"]
  ["object" "patch" "set-data"]
  ["object" "put"]
  ["object" "stat"]
  ["p2p"]
  ["p2p" "close"]
  ["p2p" "forward"]
  ["p2p" "listen"]
  ["p2p" "ls"]
  ["p2p" "stream"]
  ["p2p" "stream" "close"]
  ["p2p" "stream" "ls"]
  ["pin"]
  ["pin" "add"]
  ["pin" "ls"]
  ["pin" "rm"]
  ["pin" "update"]
  ["pin" "verify"]
  ["ping"]
  ["pubsub"]
  ["pubsub" "ls"]
  ["pubsub" "peers"]
  ["pubsub" "pub"]
  ["pubsub" "sub"]
  ["refs"]
  ["refs" "local"]
  ["repo"]
  ["repo" "fsck"]
  ["repo" "gc"]
  ["repo" "stat"]
  ["repo" "verify"]
  ["repo" "version"]
  ["resolve"]
  ["shutdown"]
  ["stats"]
  ["stats" "bitswap"]
  ["stats" "bw"]
  ["stats" "repo"]
  ["swarm"]
  ["swarm" "addrs"]
  ["swarm" "addrs" "listen"]
  ["swarm" "addrs" "local"]
  ["swarm" "connect"]
  ["swarm" "disconnect"]
  ["swarm" "filters"]
  ["swarm" "filters" "add"]
  ["swarm" "filters" "rm"]
  ["swarm" "peers"]
  ["tar"]
  ["tar" "add"]
  ["tar" "cat"]
  ["update"]
  ["urlstore"]
  ["urlstore" "add"]
  ["version"]])
